# Generated by Django 2.0.13 on 2019-03-17 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_specifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.AlterField(
            model_name='post',
            name='specifications',
            field=models.ImageField(blank=True, null=True, upload_to='imagen_specifications'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='fk_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
