# Generated by Django 2.0.13 on 2019-03-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190317_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='text',
            new_name='coment',
        ),
        migrations.AlterField(
            model_name='post',
            name='specifications',
            field=models.ImageField(null=True, upload_to='imagen_specifications'),
        ),
    ]
